"""add en_visible to fixed_pages

Revision ID: 5a97f7519557
Revises: aa36e324fc54
Create Date: 2026-03-05 18:00:26.837096

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5a97f7519557'
down_revision = 'aa36e324fc54'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('fixed_pages', schema=None) as batch_op:
        batch_op.add_column(sa.Column('en_visible', sa.Boolean(), server_default=sa.text('true'), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('fixed_pages', schema=None) as batch_op:
        batch_op.drop_column('en_visible')

    # ### end Alembic commands ###
