"""add user profile fields

Revision ID: 5cf3668f53ab
Revises: 40b3f55a034c
Create Date: 2026-02-25 17:16:33.080450

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5cf3668f53ab'
down_revision = '40b3f55a034c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('gender', sa.String(length=10), nullable=True))
        batch_op.add_column(sa.Column('age_range', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('address', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('occupation', sa.String(length=20), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('occupation')
        batch_op.drop_column('address')
        batch_op.drop_column('age_range')
        batch_op.drop_column('gender')

    # ### end Alembic commands ###
