"""add nav_type to fixed_pages

Revision ID: 7952d0457da8
Revises: 2fb68c5968de
Create Date: 2026-02-22 20:44:28.127368

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7952d0457da8'
down_revision = '2fb68c5968de'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('fixed_pages', schema=None) as batch_op:
        batch_op.add_column(sa.Column('nav_type', sa.String(length=10), nullable=False, server_default='global'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('fixed_pages', schema=None) as batch_op:
        batch_op.drop_column('nav_type')

    # ### end Alembic commands ###
