"""add summary to memos

Revision ID: a193282658e0
Revises: 5cf3668f53ab
Create Date: 2026-02-25 20:26:04.589571

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a193282658e0'
down_revision = '5cf3668f53ab'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('memos', schema=None) as batch_op:
        batch_op.add_column(sa.Column('summary', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('memos', schema=None) as batch_op:
        batch_op.drop_column('summary')

    # ### end Alembic commands ###
