"""add en_title to fixed_pages

Revision ID: aa36e324fc54
Revises: e89af17c6dab
Create Date: 2026-03-05 14:20:10.347675

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'aa36e324fc54'
down_revision = 'e89af17c6dab'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('fixed_pages', schema=None) as batch_op:
        batch_op.add_column(sa.Column('en_title', sa.String(length=100), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('fixed_pages', schema=None) as batch_op:
        batch_op.drop_column('en_title')

    # ### end Alembic commands ###
