"""add thumbnail to users

Revision ID: bd7fbecdb75a
Revises: 14eaa6d2ae7c
Create Date: 2026-02-05 13:15:19.970183

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bd7fbecdb75a'
down_revision = '14eaa6d2ae7c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('thumbnail', sa.String(length=50), nullable=False))
        batch_op.alter_column('password',
               existing_type=sa.VARCHAR(length=12),
               type_=sa.String(length=120),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('password',
               existing_type=sa.String(length=120),
               type_=sa.VARCHAR(length=12),
               existing_nullable=False)
        batch_op.drop_column('thumbnail')

    # ### end Alembic commands ###
