"""add view_count and ai_score to memos

Revision ID: e0a99c1b1340
Revises: 67b46a88cb63
Create Date: 2026-02-22 14:23:04.818791

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e0a99c1b1340'
down_revision = '67b46a88cb63'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('memos', schema=None) as batch_op:
        batch_op.add_column(sa.Column('view_count', sa.Integer(), nullable=False, server_default='0'))
        batch_op.add_column(sa.Column('ai_score', sa.JSON(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('memos', schema=None) as batch_op:
        batch_op.drop_column('ai_score')
        batch_op.drop_column('view_count')

    # ### end Alembic commands ###
