"""add AppLog table

Revision ID: e89af17c6dab
Revises: a193282658e0
Create Date: 2026-03-02 09:17:21.895388

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e89af17c6dab'
down_revision = 'a193282658e0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('app_logs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('level', sa.String(length=10), nullable=False),
    sa.Column('module', sa.String(length=100), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('app_logs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_app_logs_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_app_logs_level'), ['level'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('app_logs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_app_logs_level'))
        batch_op.drop_index(batch_op.f('ix_app_logs_created_at'))

    op.drop_table('app_logs')
    # ### end Alembic commands ###
