"""add suspend_requested and suspend_reason to users

Revision ID: f316098a208d
Revises: 7952d0457da8
Create Date: 2026-02-24 14:41:55.737625

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f316098a208d'
down_revision = '7952d0457da8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('suspend_requested', sa.Boolean(), nullable=False, server_default=sa.false()))
        batch_op.add_column(sa.Column('suspend_reason', sa.String(length=500), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('suspend_reason')
        batch_op.drop_column('suspend_requested')

    # ### end Alembic commands ###
